-- MySQL Script generated by MySQL Workbench
-- Mon Aug 24 12:38:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema heroku_baf632cb15a3418
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_baf632cb15a3418
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_baf632cb15a3418` DEFAULT CHARACTER SET utf8 ;
USE `heroku_baf632cb15a3418` ;

-- -----------------------------------------------------
-- Table `heroku_baf632cb15a3418`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_baf632cb15a3418`.`Member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `gender` ENUM('M', 'W') NOT NULL,
  `phonenumber` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_baf632cb15a3418`.`TrainingEntry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_baf632cb15a3418`.`TrainingEntry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trainingDate` DATE NOT NULL,
  `startTime` DATETIME NOT NULL,
  `created` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `Member`
    FOREIGN KEY (`id`)
    REFERENCES `heroku_baf632cb15a3418`.`Member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_baf632cb15a3418`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_baf632cb15a3418`.`Area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `labelling` VARCHAR(45) NOT NULL,
  `maxNumberOfPeople` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_baf632cb15a3418`.`Timeslot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_baf632cb15a3418`.`Timeslot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_baf632cb15a3418`.`AreaTrainingEntry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_baf632cb15a3418`.`AreaTrainingEntry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `AreaId`
    FOREIGN KEY (`id`)
    REFERENCES `heroku_baf632cb15a3418`.`Area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TrainingEntryId`
    FOREIGN KEY (`id`)
    REFERENCES `heroku_baf632cb15a3418`.`TrainingEntry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Timeslot`
    FOREIGN KEY (`id`)
    REFERENCES `heroku_baf632cb15a3418`.`Timeslot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
